### ISSUE TITLE
Which tokenizer should be used while finetuning the model on a downstream task?

### ISSUE THREAD

**Issue by ekdnam** [nipunsadvilkar/roberta-base-mr#2]
I am trying to load the model with [simpletransformers](https://github.com/ThilinaRajapakse/simpletransformers) as a `ClassificationModel`. 

While doing so, one has to specify 

1. type of tokenizer (for example `bert`, `albert`, `roberta`)
2. name of tokenizer (for example `ai4bharat/indic-bert`)

While using `roberta-base-mr` or `mr-indicnlp-classifier`, which tokenizer should one use with respect to the specifications mentioned above?

**Comment by nipunsadvilkar** [comment]
Not sure about `simpletransformers` API but you should use `roberta` as tokenizer type.

If you need more details, I would recommend importing model using 🤗 's [AutoTokenizer](https://huggingface.co/transformers/model_doc/auto.html#autotokenizer) and see attributes of `tokenizer` object to get required info above.

Reference scripts:
https://github.com/nipunsadvilkar/roberta-base-mr/blob/main/indicnlp_classifier.py#L18

Feel free to reopen the issue if you still have doubts
